import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/components/theme/theme-provider";
import Header from "@/components/header/header";
import { ScrollArea } from "@/components/ui/scroll-area";
import Footer from "@/components/footer/footer";
import FaviconUpdater from "@/components/theme/favicon-updater";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
	icons: {
		icon: [
			{
				media: "(prefers-color-scheme: light)",
				url: "/logo_cv_64_64_b_light.svg", // Path to your light mode icon
			},
			{
				media: "(prefers-color-scheme: dark)",
				url: "/logo_cv_64_64_b_dark.svg", // Path to your dark mode icon
			},
		],
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="pl" suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					<FaviconUpdater />
					<Header />
					{children}
					<Footer />
				</ThemeProvider>
			</body>
		</html>
	);
}
